name: homebrew

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["release-please"]
    types:
      - completed

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine release tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$(gh release view --json tagName -q .tagName)" >> \
              "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_RELEASE_PAT }}
      - uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          formula: toolbelt
          tap: stianfro/homebrew-toolbelt
          tag: ${{ steps.get_tag.outputs.tag }}
