name: homebrew

on:
  release:
    types: [published]

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          formula: toolbelt
          tap: stianfro/homebrew-toolbelt
          tag: ${{ github.event.release.tag_name }}
