name: homebrew

on:
  release:
    types: [published]
  workflow_run:
    workflows: ["release-please"]
    types:
      - completed

permissions:
  contents: read
  actions: read

jobs:
  bump-formula:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine release tag
        id: get_tag
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "tag=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$(gh release view --json tagName -q .tagName)" >> \
              "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump Homebrew formula
        env:
          HOMEBREW_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ steps.get_tag.outputs.tag }}
        run: |
          git clone --depth 1 https://x-access-token:${HOMEBREW_TOKEN}@github.com/stianfro/homebrew-toolbelt.git
          cd homebrew-toolbelt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          FORMULA=Formula/toolbelt.rb
          URL="https://github.com/stianfro/toolbelt/archive/refs/tags/${TAG_NAME}.tar.gz"
          curl -Ls "$URL" -o toolbelt.tar.gz
          SHA=$(shasum -a 256 toolbelt.tar.gz | awk '{print $1}')
          sed -i -E "s|url \".*\"|url \"${URL}\"|" $FORMULA
          sed -i -E "s|sha256 \".*\"|sha256 \"${SHA}\"|" $FORMULA
          git add $FORMULA
          git commit -m "toolbelt ${TAG_NAME}"
          git push origin HEAD:main
